apiVersion: v1
kind: ConfigMap
metadata:
  name: student-portal-config
  namespace: testing-stuff
  labels:
    app: student-portal
data:
  DB_LINK: "postgresql://studentportal:studentportal123@postgres:5432/studentportal"
  FLASK_ENV: "development"
