sonar.projectKey=student-portal-ecs-infra
sonar.projectName=Student Portal ECS Infrastructure
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.terraform/**,**/vars/**,**/*.tfvars,**/*.tfbackend,**/*.lock.hcl

sonar.sourceEncoding=UTF-8
