apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Maximum number of pods that can be created above desired replicas
      maxUnavailable: 0  # Maximum number of pods that can be unavailable during update
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      imagePullSecrets:
      - name: aws-secret
      containers:
      - name: attendance-app
        image: 366140438193.dkr.ecr.ap-south-1.amazonaws.com/student-portal:day12
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_LINK
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_LINK
---
apiVersion: v1
kind: Service
metadata:
  name: portal
spec:
  selector:
    app: portal
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
