apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: testing-stuff
type: Opaque
stringData:
  POSTGRES_USER: studentportal
  POSTGRES_PASSWORD: studentportal123
  POSTGRES_DB: studentportal
