name: Deploy ECS Infra Prod 

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-prod:
    uses: akhileshmishrabiz/akhilesh-github-action-library/.github/workflows/terraform-apply.yaml@main
    with:
      working-directory: ecs-infra
      environment: prod
      terraform-version: '1.8.1'
      aws-region: ap-south-1
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}