apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-app
  template:
    metadata:
      labels:
        app: attendance-app
    spec:
      containers:
      - name: attendance-app
        image: attendance-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DB_LINK
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-url
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-app
spec:
  selector:
    app: attendance-app
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
