name: terraform-infra-scan

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "ecs-infra/**"
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - "ecs-infra/**"
  workflow_dispatch:

env:
  TF_PATH: "ecs-infra"

jobs:
  terraform-infra-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ env.TF_PATH }}
          framework: terraform
          quiet: true
          soft_fail: false
          output_format: cli
          skip-check: CKV_AWS_91,CKV_AWS_2